apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-realworld-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-realworld-deployment
  template:
    metadata:
      labels:
        app: kubernetes-realworld-deployment
    spec:
      containers:
      - name: kubernetes-realworld-application
        image: fredrik/kubernetes-realworld
        ports:
          - containerPort: 3000
